import java.awt.Image;
import java.io.File;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.nio.file.*;
import java.io.IOException;


public class CekCuacaSederhana extends javax.swing.JFrame {
    
    DefaultTableModel model;

    /**
     * Creates new form CekCuacaSederhana
     */
    public CekCuacaSederhana() {
        initComponents();
        aturTabel();
        muatFavorit();
        this.setLocationRelativeTo(null);
    }
    
    private void aturTabel() {
        String[] kolom = {"Kota", "Suhu (°C)", "Keterangan", "Waktu"};
        model = new DefaultTableModel(kolom, 0);
        tblWeather.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        lblFavorit = new javax.swing.JLabel();
        comboFavorites = new javax.swing.JComboBox<>();
        lblKota = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        btnCheck = new javax.swing.JButton();
        btnAddFav = new javax.swing.JButton();
        lblCity = new javax.swing.JLabel();
        lblTemp = new javax.swing.JLabel();
        lblDesc = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        btnSaveCSV = new javax.swing.JButton();
        btnLoadCSV = new javax.swing.JButton();
        scrollTable = new javax.swing.JScrollPane();
        tblWeather = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        lblIcon = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblFavorit.setText("Favorit:");

        comboFavorites.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboFavoritesActionPerformed(evt);
            }
        });

        lblKota.setText("Kota:");

        btnCheck.setText("Cek Cuaca");
        btnCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckActionPerformed(evt);
            }
        });

        btnAddFav.setText("Tambah Ke Favorit");
        btnAddFav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddFavActionPerformed(evt);
            }
        });

        lblCity.setText("Kota:");

        lblTemp.setText("Suhu:");

        lblDesc.setText("Kondisi:");

        lblTime.setText("Waktu:");

        btnSaveCSV.setText("Simpan Riwayat Ke CSV");
        btnSaveCSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveCSVActionPerformed(evt);
            }
        });

        btnLoadCSV.setText("Muat CSV");
        btnLoadCSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadCSVActionPerformed(evt);
            }
        });

        tblWeather.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollTable.setViewportView(tblWeather);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(lblIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(lblIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSaveCSV)
                        .addGap(65, 65, 65)
                        .addComponent(btnLoadCSV, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblFavorit, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(31, 31, 31)
                                        .addComponent(btnAddFav, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(comboFavorites, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblKota, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lblTime, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblCity, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblTemp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblDesc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)))
                        .addGap(21, 21, 21)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addComponent(scrollTable)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFavorit)
                            .addComponent(comboFavorites, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblKota)
                            .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCheck)
                            .addComponent(btnAddFav))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblCity)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTemp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDesc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTime))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollTable, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSaveCSV)
                    .addComponent(btnLoadCSV))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckActionPerformed
        String city = txtCity.getText().trim();
    if (city.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Masukkan nama kota!");
        return;
    }

    try {
        WeatherData data = LogikaCekCuacaSederhana.ambilDataCuaca(city);
        lblCity.setText("Kota: " + data.getCity());
        lblTemp.setText(String.format("Suhu: %.1f °C", data.getTempC()));
        lblDesc.setText("Kondisi: " + data.getDescription());
        lblTime.setText("Waktu: " + LogikaCekCuacaSederhana.formatWaktu(data.getTimestamp()));

        // Ambil ikon dari internet
        Image img = ImageIO.read(new URL(LogikaCekCuacaSederhana.urlIkon(data.getIconCode())));
        lblIcon.setIcon(new ImageIcon(img.getScaledInstance(80, 80, Image.SCALE_SMOOTH)));

        // Tambahkan ke tabel
        DefaultTableModel model = (DefaultTableModel) tblWeather.getModel();
        model.addRow(new Object[]{
            data.getCity(),
            String.format("%.1f", data.getTempC()),
            data.getDescription(),
            LogikaCekCuacaSederhana.formatWaktu(data.getTimestamp())
        });

    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Gagal mengambil data cuaca: " + ex.getMessage());
    }
    }//GEN-LAST:event_btnCheckActionPerformed

    private void btnAddFavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddFavActionPerformed
     String city = txtCity.getText().trim();
    if (city.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Masukkan nama kota terlebih dahulu!");
        return;
    }

    comboFavorites.addItem(city);

    // Simpan semua favorit ke file
    List<String> favorit = new ArrayList<>();
    for (int i = 0; i < comboFavorites.getItemCount(); i++) {
        String item = comboFavorites.getItemAt(i);
        if (!item.equals("Pilih Favorit...")) {
            favorit.add(item);
        }
    }

    LogikaCekCuacaSederhana.simpanFavorit(favorit);
    JOptionPane.showMessageDialog(this, "Kota '" + city + "' disimpan ke daftar favorit!");

    }//GEN-LAST:event_btnAddFavActionPerformed

    private void btnSaveCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveCSVActionPerformed
         JFileChooser fc = new JFileChooser();
    if (fc.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
        File file = fc.getSelectedFile();
        try {
            DefaultTableModel model = (DefaultTableModel) tblWeather.getModel();
            LogikaCekCuacaSederhana.simpanCSV(file, model);
            JOptionPane.showMessageDialog(this, "Data berhasil disimpan ke: " + file.getAbsolutePath());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal menyimpan: " + e.getMessage());
        }
    }

    }//GEN-LAST:event_btnSaveCSVActionPerformed

    private void btnLoadCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadCSVActionPerformed
          JFileChooser fc = new JFileChooser();
    if (fc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
        File file = fc.getSelectedFile();
        try {
            DefaultTableModel model = (DefaultTableModel) tblWeather.getModel();
            LogikaCekCuacaSederhana.muatCSV(file, model);
            JOptionPane.showMessageDialog(this, "Data dari CSV berhasil dimuat!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal memuat CSV: " + e.getMessage());
        }
    }
    }//GEN-LAST:event_btnLoadCSVActionPerformed

    private void comboFavoritesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboFavoritesActionPerformed
     String sel = (String) comboFavorites.getSelectedItem();
    if (sel != null && !sel.equals("Pilih Favorit...")) {
        txtCity.setText(sel);
    }
    
    }//GEN-LAST:event_comboFavoritesActionPerformed
// Method untuk memuat kota favorit dari file ke combo box
private void muatFavorit() {
    try {
        // Ambil daftar favorit dari LogikaCekCuacaSederhana
        List<String> favs = LogikaCekCuacaSederhana.muatFavorit();

        // Tambahkan ke combo box
        for (String f : favs) {
            comboFavorites.addItem(f);
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal memuat daftar favorit: " + e.getMessage());
    }
}


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CekCuacaSederhana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CekCuacaSederhana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CekCuacaSederhana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CekCuacaSederhana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CekCuacaSederhana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddFav;
    private javax.swing.JButton btnCheck;
    private javax.swing.JButton btnLoadCSV;
    private javax.swing.JButton btnSaveCSV;
    private javax.swing.JComboBox<String> comboFavorites;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblDesc;
    private javax.swing.JLabel lblFavorit;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblKota;
    private javax.swing.JLabel lblTemp;
    private javax.swing.JLabel lblTime;
    private javax.swing.JScrollPane scrollTable;
    private javax.swing.JTable tblWeather;
    private javax.swing.JTextField txtCity;
    // End of variables declaration//GEN-END:variables
}
